// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr6AQ9dcW8z6W7dnmtmzDEPOyqyz_LGyY',
    appId: '1:401762111130:web:1949403e1cfbdfbfbb1923',
    messagingSenderId: '401762111130',
    projectId: 'cicd-a72a7',
    authDomain: 'cicd-a72a7.firebaseapp.com',
    storageBucket: 'cicd-a72a7.firebasestorage.app',
    measurementId: 'G-468N9RBS4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB36sfS0sbCRvl3tdbgcedGSzpud0PREP0',
    appId: '1:401762111130:android:b8fbf4d3da65354bbb1923',
    messagingSenderId: '401762111130',
    projectId: 'cicd-a72a7',
    storageBucket: 'cicd-a72a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrNPlHTFsW69PuFuAJGgasegckHpZxc-4',
    appId: '1:401762111130:ios:4bc1dd00a7d6bff6bb1923',
    messagingSenderId: '401762111130',
    projectId: 'cicd-a72a7',
    storageBucket: 'cicd-a72a7.firebasestorage.app',
    androidClientId: '401762111130-1le5pldogmq4vq5tk26da02q6blqp1kc.apps.googleusercontent.com',
    iosClientId: '401762111130-6ep54menm91hlsl084cksansfh79bmvn.apps.googleusercontent.com',
    iosBundleId: 'com.salih.cicdSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrNPlHTFsW69PuFuAJGgasegckHpZxc-4',
    appId: '1:401762111130:ios:4bc1dd00a7d6bff6bb1923',
    messagingSenderId: '401762111130',
    projectId: 'cicd-a72a7',
    storageBucket: 'cicd-a72a7.firebasestorage.app',
    androidClientId: '401762111130-1le5pldogmq4vq5tk26da02q6blqp1kc.apps.googleusercontent.com',
    iosClientId: '401762111130-6ep54menm91hlsl084cksansfh79bmvn.apps.googleusercontent.com',
    iosBundleId: 'com.salih.cicdSample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr6AQ9dcW8z6W7dnmtmzDEPOyqyz_LGyY',
    appId: '1:401762111130:web:7bc2b1dc7d2b9c7fbb1923',
    messagingSenderId: '401762111130',
    projectId: 'cicd-a72a7',
    authDomain: 'cicd-a72a7.firebaseapp.com',
    storageBucket: 'cicd-a72a7.firebasestorage.app',
    measurementId: 'G-QNRFCZK4SW',
  );

}