// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW0x0CjqumTgUVCOWpZxgM_9BQt0FCt7k',
    appId: '1:1050744471374:web:8ce5bb14d56c838bbde81f',
    messagingSenderId: '1050744471374',
    projectId: 'cicd-66360',
    authDomain: 'cicd-66360.firebaseapp.com',
    storageBucket: 'cicd-66360.firebasestorage.app',
    measurementId: 'G-6HQ05FSLL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZx8y0AMo7f21qWjrS1i7tHgUj0Vqh1ss',
    appId: '1:1050744471374:android:4abf72b74491788dbde81f',
    messagingSenderId: '1050744471374',
    projectId: 'cicd-66360',
    storageBucket: 'cicd-66360.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASd6PIuezKUwa5S9sa6Lzxo0Q38tqyduY',
    appId: '1:1050744471374:ios:ff6ae612abd45548bde81f',
    messagingSenderId: '1050744471374',
    projectId: 'cicd-66360',
    storageBucket: 'cicd-66360.firebasestorage.app',
    iosBundleId: 'com.example.week28',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASd6PIuezKUwa5S9sa6Lzxo0Q38tqyduY',
    appId: '1:1050744471374:ios:ff6ae612abd45548bde81f',
    messagingSenderId: '1050744471374',
    projectId: 'cicd-66360',
    storageBucket: 'cicd-66360.firebasestorage.app',
    iosBundleId: 'com.example.week28',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW0x0CjqumTgUVCOWpZxgM_9BQt0FCt7k',
    appId: '1:1050744471374:web:0238f03917c8f1cebde81f',
    messagingSenderId: '1050744471374',
    projectId: 'cicd-66360',
    authDomain: 'cicd-66360.firebaseapp.com',
    storageBucket: 'cicd-66360.firebasestorage.app',
    measurementId: 'G-0V7HJJZR31',
  );
}
