name: Flutter CI Pipeline

on: 
  push:
    branches: [main]

jobs:
  build:
    name: Build and Test Flutter App
    runs-on: ubuntu-latest

    steps:
      - names: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.x'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter Tests
        run: flutter Test

      - name: Analyze code
        run: flutter analyze

      - name: Run Tests
        run: flutter test --coverage

      # - name: Build APK
      #   run: flutter build appbundle --release

      